services:
  - type: web
    name: ecomsearch-search-api
    runtime: docker
    dockerfilePath: ./Dockerfile.api
    dockerContext: .
    plan: free
    envVars:
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: QDRANT_COLLECTION_NAME
        sync: false
      - key: QDRANT_IMAGE_COLLECTION_NAME
        sync: false
      - key: HF_DATASET_REPO
        sync: false
      - key: HF_TOKEN
        sync: false
